### PR TITLE
Converter refactor

### PR DESCRIPTION
**Pull request by JR-Morgan**
The current Unity implementation of `RecursiveConverter` was written with only .NET objects in mind
And doesn't properly convert custom object models.

The main issue we were facing is with IFC imported geometry.

I have refactored the `RecursiveConverter` class to operate more similar to how it does in our Unreal Engine connector.
I also think it's a much cleaner approach (but happy to discuss this)

### CODE REVIEW

**Comment by JR-Morgan** [comment]
@haitheredavid I would appreciate if you could take a look at this change (at some point, no rush), since this one might cause you some conflicts that you'd rather I dealt with.

**Comment by haitheredavid** [comment]
@JR-Morgan thanks for the tag - I did a quick a look and the overall logic seems pretty similar. The only thing I would point out is the use of `RecursiveConverter` as a `MonoBehaviour`. This component is only used from within the `Receiver` component, while the [`Sender`](https://github.com/specklesystems/speckle-unity/blob/672865ed8744ea981dd41c16951b547fca064f75/Packages/systems.speckle.speckle-unity/Sender.cs#L53) component   handles all of that tree behavior, so it feels a bit weird to have another mono object just for handling those commands but this could just be my personal approach to unity. I tend to lean towards only using mono objects if that component needs to relay on unity's runtime methods (i.e. Start, Update, OnEnable, etc.)

**Comment by JR-Morgan** [comment]
@haitheredavid I'm tempted to combine the ToSpeckle and ToNative recursive conversion into this class. I think that would be nice in consolidating shared behaviour.

I kept it a `monobehaviour` for now, because I'm thinking we might need to expose some properties/settings for conversion. But if we don't end up doing this, then I see no reason to keep it as a `monobehaviour` 😁

**Comment by JR-Morgan** [comment]
Closed as changes have been incorporated in #75

**Pull request closed without merging**
