### PR TITLE
Upstream/serializable properties fix

### PR DESCRIPTION
**Pull request by haitheredavid**
Mentioned in the last comment of #27, the callbacks from `ISerializationCallbackReceiver` was calling `Operation.Serialize()` every frame (in editor and playmode) whenever you clicked on a gameobject with `SpeckleProperties`. I kept the same structure started with #29 but with a couple of added classes that observe the collection and k+v.

### CODE REVIEW

**Comment by haitheredavid** [comment]
@JR-Morgan also, should I push this commit to a different branch? Seems like `main` is the one you're working with.

**Comment by JR-Morgan** [comment]
Your right, it seems like `ObservableDictionary` isn't avaiable to .NET Standard 2.0.
It might be possible to add it as a DLL.
The performance improvement might be quite neglegable however, so may not be worth.

I'll do some local testing of this PR over the weekend, and merge to `editor2`, from there I will merge it into `main` when it's ready.

**Review by JR-Morgan — APPROVED** [review]

**Comment by JR-Morgan** [comment]
Hi @haitheredavid,

Thank you for your patience, I've been caught up on the Unreal side for a while now, so I apologise for being sluggish to propertly review this.

You're right, `OnBeforeSerialize` is being called every frame while inspected 😱.

I've taken a dive into your changes, and I'm not sure I like how many times the dictionary has to be copied.
Here for example, `sd.Data` requires a new dictionary to be created each time.
https://github.com/specklesystems/speckle-unity/blob/c3de6a49a8ae6728508df8e70fb34b6ab1b3c78a/Assets/Speckle%20Connector/ConverterUnity.Geometry.cs#L447-L457

I see you've sort of solved this with the index operator.
https://github.com/specklesystems/speckle-unity/blob/5b07a84709d9922ac861a9e3cab016b12cec0efb/Assets/Speckle%20Connector/SpeckleProperties.cs#L22-L26
But something like `sp.Data.Add(foo, bar)` would still not work as expected.


I've done some more digging into `ObservableConcurrentDictionary` and I've taken a pass at an implementation using it.

I'm interested in getting your thoughts, does this solve everything we want?
I'm thinking that avoiding `SpeckleProperties.Data` from having to recreate a dictionary offers maximum flexibility, which this gives, while allowing us to perform serialisation smartly.

**Comment by haitheredavid** [comment]
hi hello @JR-Morgan ! Sorry for taking a bit to get back to you, been away on the honeymoon 🏖️, but I'm back in action 🚀. 

 I like the solution you have developed with #50, it's much cleaner 🧹 than what I had put together. It seems like this solution does what we want it to do. I also want to note that I haven't utilized  `properties` to much within unity so I might not have a well rounded perspective on how I would want them to work in untiy, but it seems like it works and gets the job done 😸. 

The one thing that might be a helpful _quality of life_ thing would be integrating a simple KVP look up for the object data. Similar to what threw together in this pr. 

```
 public object this[string key] 
 { 
   get => _data[key]; 
   set => _data[key] = value; 
 }  
```

**Comment by JR-Morgan** [comment]
Hi David!,
I hope you enjoyed your honeymoon! Congrats. 😁 

I think I'll go ahead and merge #50 now.
We can consider adding some quality of life methods later I think, that's not a bad suggestion.
I'll try and take a look at your #53 #54 PRs soon, but I have some other higher priorities,
Thank you for your contributions, and your patience!

**Comment by haitheredavid** [comment]
@JR-Morgan thanks! As I mentioned in my last post, this feature is not something I typically rely on within unity at the moment. I would rather see support for (#56 )Kits and Converters as not having access to this in the unity package is major blocker (at least for me!).

**Pull request merged**
